### ISSUE TITLE
"Cancel" button on "Edit" page non-responsive in Safari

### ISSUE THREAD

**Issue by jonpacker** [maghoff/sausagewiki#30]
Cancel button seems to be broken in Safari. When clicking it I get a javascript error in the console, that looks like this:

![image](https://user-images.githubusercontent.com/678101/32164951-451d6dfa-bd61-11e7-81bd-31476dec132d.png)

That takes me here in the code:

![image](https://user-images.githubusercontent.com/678101/32164986-7833793c-bd61-11e7-89c1-891515d6c263.png)

**Comment by maghoff** [comment]
The problem seems to be that undefined is not a function. It should be.

On a more serious note, I am unable to reproduce this error :(

**Comment by maghoff** [comment]
I am apparently using Safari version 11.0 (12604.1.38.1.7). Which version are you on?

**Comment by jonpacker** [comment]
10.1.1. That's most likely the problem then. I'll update safari and reopen this if I can reproduce it then.

**Comment by maghoff** [comment]
Ok. Well, I'll introduce a compile step for JS (and CSS) at some point. A _little_ bit of backwards compatibility can't be bad :)
