### ISSUE TITLE
Feature request: Repository backend

### ISSUE THREAD

**Issue by icefoxen** [maghoff/sausagewiki#39]
Would it be at all feasible to make it use a git or mercurial repository to store the pages?

If I made a PR adding this functionality, would you be interested?

**Comment by maghoff** [comment]
Hi! Thanks for your interest :)

I don't think that would be a great fit for Sausagewiki. It has been designed around the SQLite database as the backend from the ground up, so I think a VCS backend would be more apporpriate for another wiki engine :)
