### ISSUE TITLE
Improve styling of tables

### ISSUE THREAD

**Issue by gulrotkake** [maghoff/sausagewiki#43]
Right now tables are expanded to the full width, which doesn't look really nice:

https://tightloop.io/i/wiki.png

**Comment by maghoff** [comment]
I'm all for better styling of tables, but it is hard to come up with a universally good style that doesn't have degenerate cases. I'd entertain suggestions, though.

**Comment by maghoff** [comment]
Note that the tables are not styled to full width, but rather allowed to grow to full width. It is the content that pushes the table out in this case, and in this case, the content ought to be shaped differently.

**Comment by gulrotkake** [comment]
How would I shape content in a markdown table without html?

*Edit: I can add extra rows with empty column data to force a linebreak in long lines, not nice, but works for now.

**Comment by maghoff** [comment]
That's a generic question to a specific suggestion ("in this case"). I was not making a generic suggestion. Perhaps we could take this discussion in person.
