### ISSUE TITLE
Upgrade to Diesel 0.99

### ISSUE THREAD

**Issue by maghoff** [maghoff/sausagewiki#49]
https://github.com/diesel-rs/diesel/releases/tag/v0.99.0

**Comment by killercup** [comment]
Awesome project! This might be the largest Diesel-SQLite codebase I've seen in the wild so far! :) Let me know if the upgrade to 0.99 is giving you any troubles. Anything SQLite-specific features you want us to prioritize?

**Comment by maghoff** [comment]
@killercup Thank you! :)

>Let me know if the upgrade to 0.99 is giving you any troubles.

I will, thanks for getting in touch :)

>Anything SQLite-specific features you want us to prioritize?

I interpret this question as a kind of probe of what goes through the minds of Diesel-SQLite-users, so I have answered accordingly, with a bit of a brain dump 😬 I hope this answer sits well with you 😁

---

I think I have one gripe which is a problem Diesel should fix, which is that `infer_schema!` fails in the presence of virtual tables (necessary for full text search). It has been reported as [issue 1112](https://github.com/diesel-rs/diesel/issues/1112), but was closed by the reporter when they found a workaround.

It is not a showstopper. I, too, have been able to work around it. Furthermore, I think fixing it would be backwards compatible, so I understand if the Diesel project would not care to prioritize it in the lead-up to 1.0.

I am using build.rs to build a SQLite db-file which in turn is used for `infer_schema!`. This is a bit round-about, but it makes the migrations the _real_ source code for my schemas, which is neat. The relevant code for the `infer_schema!` workaround is here: https://github.com/maghoff/sausagewiki/blob/master/build.rs#L34-L42

Ideally, those lines would just be the one line `infer_schema!(#db_path);` instead, as they [did before I added full text search](https://github.com/maghoff/sausagewiki/commit/1bb1df8cf0c030970ed75aee168bc8070eb636d5#diff-a7b0a2dee0126cddf994326e705a91eaL33).

---

Some [full text search](https://github.com/maghoff/sausagewiki/blob/0f835fa312436f030ea7d64036a704b59fb75b7a/src/state.rs#L366-L401) support would be nice. Query builder for the FTS syntax? However, the `sql` (soon `sql_query`) escape hatch is sufficient to get by.

---

Being able to [register custom functions](https://github.com/diesel-rs/diesel/issues/1103) with SQLite would let me do some [valuable](https://github.com/maghoff/sausagewiki/issues/37) [things](https://github.com/maghoff/sausagewiki/issues/38). I was thinking I might attempt to contribute a solution to that ticket when I get around to it, but I cannot promise that I'll be able to prioritize it anytime soon.

---

I think that's it for this brain dump 🙂 I am very happy with using Diesel and SQLite. I sometimes find the documentation wanting, but that is understandable for the maturity level of Diesel, unfortunately. Thank you for Diesel 🙂

**Comment by maghoff** [comment]
@killercup I'm now at Diesel 1.0.0-beta1, and upgrading went smooth!

I had one problem. My upgrade plan was to upgrade to 0.99, fix all warnings and then upgrade to 1. I had problems using `sql_query` with version 0.99, because I was unable to use [`#[sql_type = ...]`-annotations](http://docs.diesel.rs/diesel/query_source/trait.QueryableByName.html) to get `#[derive(QueryableByName)]` working. It seems that `#[derive(QueryableByName)]` must be used with a table definition in Diesel 0.99?

I opted to upgrade directly to version 1 without fixing all the warnings first, which panned out. But I suspect this might be a problem others will also bump into.

**Comment by killercup** [comment]
@maghoff I'm glad it went smooth for you!

Yeah, these are basically the only differences between 0.99 and 1.0 beta (see [change log](https://github.com/diesel-rs/diesel/blob/8934d5b50b51bdb0c1a016ab5adeba0b154381aa/CHANGELOG.md#added)). As we already removed all deprecated items at that point, back porting this changes wasn't trivial. (And of course the very difficult choice how to name a release that follows 0.99! 0.999?) I personally hope that people will just move to 1.0 and that the number of people who go to 0.99 _and_ use advanced features isn't that high :)

**Comment by sgrif** [comment]
You can also implement the trait by hand, which is what I did on crates.io updating to 0.99. You can look at their code base to see some examples
