### ISSUE TITLE
There should be [readonly] online demo.

### ISSUE THREAD

**Issue by vi** [maghoff/sausagewiki#51]
Maybe there should also be a global `--readonly` command-line flag.

From "Works with external authentication" README point I assume there are user accounts, so I assume read-only status can already be set per user.

**Comment by maghoff** [comment]
Sorry, no.

**Comment by vi** [comment]
Is it that insecure so that even a readonly version is a threat?

That published, then retracted (without explanation) online demo can make one scared to run it even locally.

**Comment by maghoff** [comment]
Not at all, I am just not interested in this idea.

**Comment by vi** [comment]
Rolled my own: https://vi-server.org/sausagewikidemo/

Can be linked from a README, but no gurantee of uptime or how long would it be running or how often get updated.
