### ISSUE TITLE
Connection was reset

### ISSUE THREAD

**Issue by fmorency** [maghoff/sausagewiki#55]
I'm trying to create a Docker image for serving *sausagewiki* but I always get "connection was reset" when attempting to reach the server.

To get it running, first install the latest version of [Docker](https://www.docker.io). Then, create an empty directory and copy
```
FROM alpine
RUN apk update && apk add curl
RUN curl -LOk $(curl -s\
    https://api.github.com/repos/maghoff/sausagewiki/releases/latest |\
    awk '/browser_download_url/ { print $2 }' |\
    sed 's/"//g') && tar Jxvf sausagewiki.tar.xz && rm sausagewiki.tar.xz
VOLUME /var/lib/
EXPOSE 8080
CMD ["/sausagewiki", "/var/lib/sausagewiki.db"]
```
to a file named `Dockerfile`. Build the container image using `docker build -t sausagewiki .` and run the newly created image using `docker run -v /var/lib:/var/lib -i -t --rm -p 8081:8080 sausagewiki`. 
You should see `Listening on http://127.0.0.1:8080` in your terminal and the file `sausagewiki.db` located in */var/lib* . Try accessing `http://127.0.0.1:8081` and notice the "connection was reset" error. 
I tried building the container using `... sausagewiki --trust-identity` but always get the same error.

Thoughts?

**Comment by maghoff** [comment]
Nice :) I don't have time to test right now, but did you try supplying `-a 0.0.0.0` (or `-a ::`) on the Sausagewiki command line? This might be necessary to be able to connect from outside the docker container, although I am not entirely clear on exactly how networking works in a Docker setting.

**Comment by maghoff** [comment]
As an aside, if you would rather parse the JSON from GitHub as JSON, instead of string manipulating it, this is the command line I use to get the latest build, with `jq` for parsing:

```
curl \
    -o sausagewiki-next.tar.xz \
    -L \
    "$(curl -L 'https://api.github.com/repos/maghoff/sausagewiki/releases' \
        | jq -r '.[0].assets[] | select(.name == "sausagewiki.tar.xz") | .browser_download_url')"
```

**Comment by maghoff** [comment]
I was able to test now, and adding the `-a` argument does indeed fix this problem.
