### ISSUE TITLE
Page trees (parents and children)

### ISSUE THREAD

**Issue by paulcmal** [maghoff/sausagewiki#59]
Right now it doesn't seem like a page can have a parent. I'm not sure if this feature would be useful for everyone, but i think it would be for me.

To me, the simplest and most meaningful implementation of page parenthood would be [breadcrumbs](https://en.wikipedia.org/wiki/Breadcrumb_(navigation)) linking to parent pages, and letting parent pages decide whether to link to children or not within the Markdown directly.

What do you think?

**Comment by maghoff** [comment]
This is not in the cards for Sausagewiki, I'm sorry. You will have to add the breadcrumbs manually.

I find rigid structures to be too imposing. For a bit of inspiration on organizing stuff without the rigid structures, see [Everything is Miscellaneaous](https://www.youtube.com/watch?v=WHeta_YZ0oE) :)

If you feel the need for namespacing, please note that multiple articles may have the same title.
