### ISSUE TITLE
Slash not allowed in slug?

### ISSUE THREAD

**Issue by paulcmal** [maghoff/sausagewiki#60]
Currently, if i try to create a page `foo/bar`, the generated slug is `foo-bar`. This is due to the way [slug](https://crates.io/crates/slug) handles slug generation. Is this intended? This is an issue for (potentially) implementing #59.

**Comment by maghoff** [comment]
This is by design. I have reserved `<slug>/...`-URLs for the system (maybe attachments in the future?)
