### ISSUE TITLE
UI: Differentiate internal and external links

### ISSUE THREAD

**Issue by paulcmal** [maghoff/sausagewiki#62]
I find it useful on a wiki to easily distinguish between internal links within the docs and links to external resources on other websites.

This is a simple addition to the CSS (HTML is untouched). A rule matching links (a tags) starting with `http` and appending an svg image just like Wikipedia does (litterally).
![sans titre](https://user-images.githubusercontent.com/3382716/40988255-ebb4fcfc-68ea-11e8-8499-c6e1c42ba837.png)

I would be happy to submit a PR if this feature is of interest to people :)

**Comment by maghoff** [comment]
I don't know if I'd like this or not. Would it be much trouble for you to create the PR, and then I could test it and evaluate if I feel that it is appropriate to include?

**Comment by paulcmal** [comment]
I opened a PR :)

Because this is for styling purposes, i would understand if you do not want to merge. But in that case, would you mind considering a theming system such as providing a replacement stylesheet on runtime? Should i open a separate issue for this or just continute to try and improve the current/default theme with PRs?

**Comment by maghoff** [comment]
Fixed by #63
