### ISSUE TITLE
HTML: Charset should be defined in the <head>

### ISSUE THREAD

**Issue by paulcmal** [maghoff/sausagewiki#67]
For general compatibility issues, it is better to specify the charset in the HTML document as well :)
```
<meta charset="utf-8">
```

**Comment by maghoff** [comment]
Thanks! Will do.

**Comment by paulcmal** [comment]
Thanks for the fix. I will close this issue now unless you see a reason not to ;)

**Comment by maghoff** [comment]
Well, the changeset was not made in `master`. GitHub would have closed this issue when the relevant branch was merged. But I don't think this minor issue is reason to reopen the ticket :)

**Comment by paulcmal** [comment]
Woops, indeed i did not notice it was on a different branch.

Slightly off-topic, but i can see you're working on re-styling/theming sausagewiki. Is this something that you would like some help with? I'd be more than happy to contribute to a modern layout based on CSS grid, or to be able to make my own theme (templates + assets). Is there a way to reach you outside of Github/Google to talk it through and see what we could or couldn't do together? (i.e. an IRC channel or Jabber MUC or something)

**Comment by maghoff** [comment]
Thanks for offering to help! Unfortunately I have to decline.

Sausagewiki is my therapy project, where I go to relax and do my own thing without worrying about everything I have to worry about at work. I'm sorry, I really just need to be able to make this how I want it without getting bogged down in communication.

User-defined theming is deliberately out of the question for Sausagewiki. There's plenty of wiki engines that offer theming. I'm making an alternative. Sorry to deny your request.
