### ISSUE TITLE
META: Semantic versioning in Github releases

### ISSUE THREAD

**Issue by paulcmal** [maghoff/sausagewiki#68]
Hey, i think it would be super useful to follow some form of semantic versioning in the [releases](https://github.com/maghoff/sausagewiki/releases). In particular, that allows people to track [from a shell script](https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c) running in a cron when new versions come out.

Usually, the standard used for versioning is semantic versioning. From [semver.org](https://semver.org) : 
>Given a version number MAJOR.MINOR.PATCH, increment the:
> * MAJOR version when you make incompatible API changes,
> * MINOR version when you add functionality in a backwards-compatible manner, and
> * PATCH version when you make backwards-compatible bug fixes.

Is this something you would be willing to do? :)

**Comment by maghoff** [comment]
I'm postponing that until Sausagewiki is more mature.
