### ISSUE TITLE
UI: Themes should have appropriate link colors

### ISSUE THREAD

**Issue by paulcmal** [maghoff/sausagewiki#70]
Currently, link colors in themes all default to `#01579b`. That makes it very ugly if not plain unreadable.
![sans titre](https://user-images.githubusercontent.com/3382716/41808994-6be86c20-76e6-11e8-839e-5a8a6a1209df.jpg)

**Comment by maghoff** [comment]
The new styling is a work in progress. There are many issues with it, especially with regards to contrast. While this is a valid issue, I don't find it helpful to track it in an issue. I'll get to it.
