### ISSUE TITLE
Exec format error on Raspberry Pi OS

### ISSUE THREAD

**Issue by ghost** [maghoff/sausagewiki#74]
I'm getting an error on startup when trying to start the May 25th release on Raspberry Pi OS.

./sausagewiki wiki.db
bash: ./sausagewiki: cannot execute binary file: Exec format error

I'm guessing either some dependencies are not fulfilled or it is a 64bit application? Raspberry Pi OS is 32bit unfortunately.

It'd be awesome if someone could shed some light on this.

**Comment by ghost** [comment]
Nevermind, compiling it locally seems to work.

**Comment by maghoff** [comment]
Yes, you need to compile it yourself for Raspberry Pi. The binary I have provided is compiled for x86-64, which is not only 64 bits, but an entirely different architecture from where you are running it.

I'd like to provide precompiled binaries for RPi as well, in the future.
